
import React from 'react';
import { UserRole, User, EducationContent, ANCVisit } from './types';
import { LayoutDashboard, Users, UserPlus, BookOpen, MapPin, QrCode, Phone, ShieldCheck, Map as MapIcon } from 'lucide-react';

export const PUSKESMAS_INFO = {
  name: "Puskesmas Pasar Minggu",
  address: "Jl. Kebagusan Raya No.4, RT.4/RW.4 12520 Jakarta Jakarta",
  phone: "+6289521868087",
  email: "kontak@puskesmas-pasarminggu.go.id",
  lat: -6.2996,
  lng: 106.8315
};

export const WILAYAH_DATA = {
  "Pasar Minggu": [
    "Pejaten Barat",
    "Pejaten Timur",
    "Pasar Minggu",
    "Kebagusan",
    "Jati Padang",
    "Ragunan",
    "Cilandak Timur"
  ]
};

export const NAVIGATION = [
  { name: 'Dashboard', icon: <LayoutDashboard size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'dashboard' },
  { name: 'Data Pasien', icon: <Users size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'patients' },
  { name: 'Monitoring Resiko', icon: <MapPin size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'monitoring' },
  { name: 'Pemetaan Lokasi', icon: <MapIcon size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'map' },
  { name: 'Pendaftaran ANC', icon: <UserPlus size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'register' },
  { name: 'Manajemen Akses', icon: <ShieldCheck size={20} />, roles: [UserRole.ADMIN], path: 'management' },
  { name: 'Kartu ANC Pintar', icon: <QrCode size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'smart-card' },
  { name: 'Edukasi Ibu', icon: <BookOpen size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'education' },
  { name: 'Kontak Kami', icon: <Phone size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'contact' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'admin',
    username: 'admin',
    password: 'admin123',
    name: 'Dr. Ahmad (Admin)',
    dob: '1980-01-01',
    address: 'Kantor Puskesmas Pasar Minggu',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pasar Minggu',
    hpht: '',
    pregnancyMonth: 0,
    pregnancyNumber: 0,
    parityP: 0,
    parityA: 0,
    medicalHistory: 'SYSTEM_ADMIN',
    role: UserRole.ADMIN,
    phone: '0812000000',
    isActive: true,
    selectedRiskFactors: [],
    totalRiskScore: 0
  },
  {
    id: 'bidan',
    username: 'bidan',
    password: 'bidan123',
    name: 'Bidan Siti, S.Tr.Keb',
    dob: '1985-03-10',
    address: 'Puskesmas Pasar Minggu',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pasar Minggu',
    hpht: '',
    pregnancyMonth: 0,
    pregnancyNumber: 0,
    parityP: 0,
    parityA: 0,
    medicalHistory: 'SYSTEM_NAKES',
    role: UserRole.NAKES,
    phone: '0813000000',
    isActive: true,
    selectedRiskFactors: [],
    totalRiskScore: 0
  },
  {
    id: 'u2',
    username: 'rina',
    password: 'u2',
    name: 'Rina Kartika',
    dob: '1992-08-20',
    address: 'Jl. Kebagusan Dalam No. 4',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Kebagusan',
    lat: -6.3100,
    lng: 106.8300,
    hpht: '2024-07-15',
    pregnancyMonth: 7,
    pregnancyNumber: 3,
    parityP: 2,
    parityA: 0,
    medicalHistory: 'Hipertensi Kronis',
    role: UserRole.USER,
    phone: '081234567802',
    isActive: true,
    selectedRiskFactors: ['PRE_ECLAMPSIA', 'HYPERTENSION'],
    totalRiskScore: 20
  },
  {
    id: 'u3',
    username: 'dewi',
    password: 'u3',
    name: 'Dewi Sartika',
    dob: '1990-05-15',
    address: 'Jl. Jati Padang Baru No. 88',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Jati Padang',
    lat: -6.2950,
    lng: 106.8400,
    hpht: '2024-09-10',
    pregnancyMonth: 5,
    pregnancyNumber: 2,
    parityP: 1,
    parityA: 0,
    medicalHistory: 'Riwayat SC 2 tahun lalu',
    role: UserRole.USER,
    phone: '081234567803',
    isActive: true,
    selectedRiskFactors: ['HISTORY_SC'],
    totalRiskScore: 8
  },
  {
    id: 'u4',
    username: 'maya',
    password: 'u4',
    name: 'Maya Indah',
    dob: '1982-11-30',
    address: 'Pejaten Estate Block C',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pejaten Timur',
    lat: -6.2880,
    lng: 106.8280,
    hpht: '2024-11-05',
    pregnancyMonth: 3,
    pregnancyNumber: 4,
    parityP: 3,
    parityA: 0,
    medicalHistory: 'Diabetes Melitus',
    role: UserRole.USER,
    phone: '081234567804',
    isActive: true,
    selectedRiskFactors: ['DIABETES', 'AGE_EXTREME'],
    totalRiskScore: 16
  },
  {
    id: 'u6',
    username: 'lia',
    password: 'u6',
    name: 'Lia Permata',
    dob: '1994-06-25',
    address: 'Cilandak Townhouse No. 5',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Cilandak Timur',
    lat: -6.2900,
    lng: 106.8100,
    hpht: '2024-06-20',
    pregnancyMonth: 8,
    pregnancyNumber: 2,
    parityP: 1,
    parityA: 0,
    medicalHistory: 'Penyakit Jantung Bawaan',
    role: UserRole.USER,
    phone: '081234567806',
    isActive: true,
    selectedRiskFactors: ['HEART_DIS'],
    totalRiskScore: 12
  }
];

export const MOCK_ANC_VISITS: ANCVisit[] = [
  // RINA KARTIKA (High Risk - Hipertensi)
  {
    id: 'v-rina-1',
    patientId: 'u2',
    visitDate: '2025-01-10',
    scheduledDate: '2025-01-10',
    nextVisitDate: '2025-02-10',
    weight: 65.5,
    bloodPressure: '145/95',
    tfu: 24,
    djj: 144,
    hb: 10.5,
    complaints: 'Sakit kepala ringan',
    dangerSigns: ['Pusing Hebat'],
    edema: true,
    fetalMovement: 'Normal',
    followUp: 'KONSUL_DOKTER',
    nakesNotes: 'Waspada Pre-eklampsia, diet rendah garam.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  {
    id: 'v-rina-2',
    patientId: 'u2',
    visitDate: '2025-02-15',
    scheduledDate: '2025-02-10',
    nextVisitDate: '2025-03-15',
    weight: 68.2,
    bloodPressure: '155/100',
    tfu: 28,
    djj: 150,
    hb: 10.2,
    complaints: 'Kaki bengkak',
    dangerSigns: ['Pusing Hebat'],
    edema: true,
    fetalMovement: 'Normal',
    followUp: 'RUJUK_RS',
    nakesNotes: 'Tekanan darah meningkat signifikan, segera rujuk ke RS untuk evaluasi spesialis.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  // DEWI SARTIKA (Moderate Risk - Riwayat SC)
  {
    id: 'v-dewi-1',
    patientId: 'u3',
    visitDate: '2025-01-20',
    scheduledDate: '2025-01-20',
    nextVisitDate: '2025-02-20',
    weight: 60.0,
    bloodPressure: '110/70',
    tfu: 20,
    djj: 138,
    hb: 11.5,
    complaints: 'Nyeri pada bekas jahitan lama',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'ANC_RUTIN',
    nakesNotes: 'Kondisi stabil, bekas SC tidak ada kelainan bermakna.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  // MAYA INDAH (High Risk - Diabetes)
  {
    id: 'v-maya-1',
    patientId: 'u4',
    visitDate: '2025-02-05',
    scheduledDate: '2025-02-05',
    nextVisitDate: '2025-03-05',
    weight: 75.0,
    bloodPressure: '130/85',
    tfu: 18,
    djj: 142,
    hb: 11.0,
    complaints: 'Sering haus dan BAK malam hari',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'KONSUL_DOKTER',
    nakesNotes: 'Kontrol gula darah ketat, kolaborasi dengan dokter penyakit dalam.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  // LIA PERMATA (Extreme Risk - Jantung)
  {
    id: 'v-lia-1',
    patientId: 'u6',
    visitDate: '2025-02-12',
    scheduledDate: '2025-02-12',
    nextVisitDate: '2025-03-12',
    weight: 55.0,
    bloodPressure: '120/80',
    tfu: 30,
    djj: 155,
    hb: 10.8,
    complaints: 'Sesak nafas saat beraktivitas ringan',
    dangerSigns: ['Pusing Hebat'],
    edema: true,
    fetalMovement: 'Kurang Aktif',
    followUp: 'RUJUK_RS',
    nakesNotes: 'Pasien sesak nafas (dispnea), risiko dekompensasi kordis. Rujuk segera.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  }
];

export const EDUCATION_LIST: EducationContent[] = [
  {
    id: 'e1',
    title: 'Gizi Seimbang Ibu Hamil',
    type: 'TEXT',
    category: 'Gizi',
    content: 'Pentingnya asupan protein, zat besi, dan asam folat selama masa kehamilan.',
    thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    url: 'https://promkes.kemkes.go.id/pentingnya-gizi-seimbang-bagi-ibu-hamil'
  }
];
